# @package _global_

defaults:
  - aleph_surg_full_ft_base
  - _self_

data:
  train_datasets:
    - "./robometer_dataset/aleph_surg/wrist_right/train/aleph_surg_wrist_right_train/train"
  eval_datasets:
    - "./robometer_dataset/aleph_surg/wrist_right/eval/aleph_surg_wrist_right_eval/eval"

training:
  exp_name: aleph_surg_fulltask_wrist_right
  gradient_checkpointing: true
